language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  include:
    - php: 7.0
      env: SYMFONY_VERSION=^3.4.0
    - php: 7.1
      env: SYMFONY_VERSION=^3.4.0
    - php: 7.2
      env: SYMFONY_VERSION=^3.4.0
  fast_finish: true

before_install:
  - composer self-update
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
